backend/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("meuapp.urls", "home"), namespace="home")),
]

meuapp/urls.py
from django.urls import path
from .views import upload

app_name = "home"
urlpatterns = [path("", upload, name="upload")]

meuapp/models.py
from django.db import models

# Create your models here.


class ModelDoArquivo(models.Model):
    nome_loja = models.CharField(max_length=26)
    valor = models.CharField(max_length=26)
    data = models.CharField(max_length=26)
    tipo = models.CharField(max_length=26)
    cartao = models.CharField(max_length=26)
    hora = models.CharField(max_length=9)
    dono = models.CharField(max_length=30)
    CPF = models.CharField(max_length=14)

meuapp/views.py
from django.shortcuts import render, redirect
from .utils import identificadores, calculadora
from .models import ModelDoArquivo
from .form import Formulario


def upload(request):
    message = "Envie o seu Arquivo aqui!"
    total = 0
    if request.method == "POST":
        form = Formulario(request.POST, request.FILES)
        if form.is_valid():
            for x in request.FILES["documento"]:
                segundo = str(x)[48:50]
                minuto = str(x)[46:48]
                hora = str(x)[44:46]
                dia = str(x)[9:11]
                mes = str(x)[7:9]
                ano = str(x)[3:7]
                obj = {
                    "tipo": identificadores(str(x)[2]),
                    "data": f"{dia}/{mes}/{ano}",
                    "valor": int(str(x)[12:21]) / 100,
                    "CPF": str(x)[21:32],
                    "cartao": str(x)[32:44],
                    "hora": f"{hora}:{minuto}:{segundo}",
                    "dono": str(x, "utf-8")[48:62],
                    "nome_loja": str(x, "utf-8")[62:80],
                }

                new_file = ModelDoArquivo(**obj)
                new_file.save()

            return redirect("upload")
        else:
            message = "Erro no formulário enviado"
    else:
        form = Formulario()

    files = ModelDoArquivo.objects.all()

    total = calculadora(files)

    context = {"files": files, "form": form, "message": message, "total": total}
    return render(request, "home.html", context)

meuapp/templates/home.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Entrega-Pedro-Soprano</title>
</head>

<body>

    {% if files %}
    <h2>Total</h2>
    <div>

        <h2>R$ {{total}}</h2>
    </div>

    <table>
        <tr>
            <th>Nome da loja</th>
            <th>Dono da loja</th>
            <th>Data</th>
            <th>Valor</th>
            <th>N° cartão</th>
            <th>Tipo</th>
            <th>CPF</th>
            <th>Hora</th>
        </tr>
        {% for file in files %}
        <tr>
            <td>{{file.nome_loja}}</td>
            <td>{{file.dono}}</td>
            <td>{{file.data}}</td>
            <td>{{file.valor}}</td>
            <td>{{file.cartao}}</td>
            <td>{{file.tipo}}</td>
            <td>{{file.CPF}}</td>
            <td>{{file.hora}}</td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
    <form action="{% url 'home:upload' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ message }}
        <p>{{ form.non_field_errors }}</p>

        <p>{{ form.documento.label_tag }}</p>

        <p class="input">
            {{ form.documento }}
        </p>

        <p><input type="submit" value="Upload" /></p>
    </form>
</body>

</html>